#!/usr/bin/env python3
"""Refresh the auto-generated news entries in index.html from ORCID.

Reads the public ORCID API (no authentication, no scraping) and rewrites the
`newsAuto` array in index.html between its BEGIN/END markers. Hand-written
items in `newsAuto`'s sibling array `news` are never touched.

Usage:  python3 tools/update_news.py [--orcid 0000-0002-9892-8282] [--max 6]
Exit 0 whether or not anything changed; prints "CHANGED" when it rewrote.
"""

import argparse
import json
import pathlib
import re
import sys
import urllib.error
import urllib.request

API = "https://pub.orcid.org/v3.0/{orcid}/works"
BEGIN = "// >>> AUTO-NEWS-BEGIN — generated by tools/update_news.py, do not edit by hand"
END = "// <<< AUTO-NEWS-END"

# ORCID metadata is author-deposited and occasionally wrong. Correct known bad
# venues here, keyed by DOI, rather than dropping the entry. Fix the underlying
# record at orcid.org too — this map is a safety net, not the cure.
VENUE_FIX = {
    "10.1021/acsami.3c08208": "ACS Applied Materials & Interfaces",
}


def fetch(orcid: str, timeout: int = 30):
    req = urllib.request.Request(
        API.format(orcid=orcid),
        headers={"Accept": "application/json", "User-Agent": "vagias-homepage/1.0"},
    )
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.load(r)


def strip_tags(s: str) -> str:
    return re.sub(r"<[^>]+>", "", s or "").strip()


def works(payload):
    out = []
    for group in payload.get("group") or []:
        summaries = group.get("work-summary") or []
        if not summaries:
            continue
        s = summaries[0]
        title = ((s.get("title") or {}).get("title") or {}).get("value")
        if not title:
            continue
        date = s.get("publication-date") or {}
        year = ((date.get("year") or {}) or {}).get("value")
        month = ((date.get("month") or {}) or {}).get("value")
        if not year:
            continue
        doi = None
        for eid in ((s.get("external-ids") or {}).get("external-id") or []):
            if (eid.get("external-id-type") or "").lower() == "doi":
                doi = (eid.get("external-id-value") or "").lower()
        journal = ((s.get("journal-title") or {}) or {}).get("value")
        if doi in VENUE_FIX:
            journal = VENUE_FIX[doi]
        out.append(
            {
                "date": f"{year}-{int(month):02d}" if month else year,
                "sort": f"{year}-{int(month):02d}" if month else f"{year}-00",
                "title": strip_tags(title),
                "journal": strip_tags(journal) if journal else None,
                "doi": doi,
            }
        )
    out.sort(key=lambda w: w["sort"], reverse=True)
    return out


def js_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def render(items) -> str:
    # The regex match starts at BEGIN itself, so the existing indent in front
    # of it survives — emitting our own here would double it.
    lines = [BEGIN]
    lines.append("    newsAuto: [")
    for w in items:
        if w["journal"]:
            text = f"New paper in <i>{w['journal']}</i>: {w['title']}."
        else:
            text = f"New paper: {w['title']}."
        url = f"https://doi.org/{w['doi']}" if w.get("doi") else ""
        lines.append(
            f'      {{ date: "{w["date"]}", url: "{url}", text: "{js_escape(text)}" }},')
    lines.append("    ],")
    lines.append(f"    {END}")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--orcid", default="0000-0002-9892-8282")
    ap.add_argument("--max", type=int, default=6)
    ap.add_argument("--file", default="index.html")
    args = ap.parse_args()

    try:
        payload = fetch(args.orcid)
    except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as e:
        # A transient ORCID outage must not fail the scheduled job or, worse,
        # blank the news list. Leave the page exactly as it is.
        print(f"ORCID unreachable ({e}); leaving index.html untouched", file=sys.stderr)
        return 0

    items = works(payload)
    if not items:
        print("ORCID returned no public works; leaving index.html untouched", file=sys.stderr)
        return 0

    path = pathlib.Path(args.file)
    src = path.read_text(encoding="utf-8")
    block = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not block.search(src):
        print("markers not found in index.html", file=sys.stderr)
        return 1

    new = render(items[: args.max])
    updated = block.sub(lambda _m: new, src, count=1)

    if updated == src:
        print("no change")
        return 0

    path.write_text(updated, encoding="utf-8")
    print(f"CHANGED — {len(items[:args.max])} entries, newest {items[0]['date']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
