#!/usr/bin/env python3
"""Refresh the auto-generated parts of index.html from public APIs.

Two blocks are rewritten in place, each between its own BEGIN/END markers:

  newsAuto  — recent publications, from the public ORCID API.
  metrics   — citation counts, from the public OpenAlex API.

Both are read without authentication or scraping. Hand-written content is never
touched: `newsAuto`'s sibling array `news`, and everything outside the markers.

Usage:  python3 tools/update_news.py [--orcid 0000-0002-9892-8282] [--max 6]
Exit 0 whether or not anything changed; prints "CHANGED" when it rewrote.
"""

import argparse
import datetime
import json
import pathlib
import re
import sys
import urllib.error
import urllib.request

API = "https://pub.orcid.org/v3.0/{orcid}/works"
BEGIN = "// >>> AUTO-NEWS-BEGIN — generated by tools/update_news.py, do not edit by hand"
END = "// <<< AUTO-NEWS-END"

# OpenAlex holds two author records carrying this ORCID: the real one, and a
# near-empty duplicate that the /authors/orcid: lookup happens to resolve to.
# Pin the canonical ID so a monthly job can never silently publish zeroes.
OPENALEX_AUTHOR = "A5000055007"
OPENALEX_API = "https://api.openalex.org/authors/{aid}"
M_BEGIN = "<!-- AUTO-METRICS-BEGIN — generated by tools/update_news.py, do not edit by hand -->"
M_END = "<!-- AUTO-METRICS-END -->"

# ORCID metadata is author-deposited and occasionally wrong. Correct known bad
# venues here, keyed by DOI, rather than dropping the entry. Fix the underlying
# record at orcid.org too — this map is a safety net, not the cure.
VENUE_FIX = {
    "10.1021/acsami.3c08208": "ACS Applied Materials & Interfaces",
}


def fetch_json(url: str, timeout: int = 30):
    req = urllib.request.Request(
        url,
        headers={"Accept": "application/json", "User-Agent": "vagias-homepage/1.0"},
    )
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.load(r)


def fetch(orcid: str, timeout: int = 30):
    return fetch_json(API.format(orcid=orcid), timeout)


def strip_tags(s: str) -> str:
    return re.sub(r"<[^>]+>", "", s or "").strip()


def works(payload):
    out = []
    for group in payload.get("group") or []:
        summaries = group.get("work-summary") or []
        if not summaries:
            continue
        s = summaries[0]
        title = ((s.get("title") or {}).get("title") or {}).get("value")
        if not title:
            continue
        date = s.get("publication-date") or {}
        year = ((date.get("year") or {}) or {}).get("value")
        month = ((date.get("month") or {}) or {}).get("value")
        if not year:
            continue
        doi = None
        for eid in ((s.get("external-ids") or {}).get("external-id") or []):
            if (eid.get("external-id-type") or "").lower() == "doi":
                doi = (eid.get("external-id-value") or "").lower()
        journal = ((s.get("journal-title") or {}) or {}).get("value")
        if doi in VENUE_FIX:
            journal = VENUE_FIX[doi]
        out.append(
            {
                "date": f"{year}-{int(month):02d}" if month else year,
                "sort": f"{year}-{int(month):02d}" if month else f"{year}-00",
                "title": strip_tags(title),
                "journal": strip_tags(journal) if journal else None,
                "doi": doi,
            }
        )
    out.sort(key=lambda w: w["sort"], reverse=True)
    return out


def js_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def render(items) -> str:
    # The regex match starts at BEGIN itself, so the existing indent in front
    # of it survives — emitting our own here would double it.
    lines = [BEGIN]
    lines.append("    newsAuto: [")
    for w in items:
        if w["journal"]:
            text = f"New paper in <i>{w['journal']}</i>: {w['title']}."
        else:
            text = f"New paper: {w['title']}."
        url = f"https://doi.org/{w['doi']}" if w.get("doi") else ""
        lines.append(
            f'      {{ date: "{w["date"]}", url: "{url}", text: "{js_escape(text)}" }},')
    lines.append("    ],")
    lines.append(f"    {END}")
    return "\n".join(lines)


def metrics_block(author_id: str):
    """Return the rewritten metrics block, or None to leave the page alone."""
    try:
        d = fetch_json(OPENALEX_API.format(aid=author_id))
    except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as e:
        print(f"OpenAlex unreachable ({e}); leaving metrics untouched", file=sys.stderr)
        return None

    stats = d.get("summary_stats") or {}
    cites = d.get("cited_by_count")
    h = stats.get("h_index")
    i10 = stats.get("i10_index")
    # Zeroes almost always mean a disambiguation split upstream rather than a
    # real collapse in citations. Publishing them would be worse than staleness.
    if not all(isinstance(v, int) and v > 0 for v in (cites, h, i10)):
        print(f"OpenAlex returned implausible metrics {cites}/{h}/{i10}; "
              "leaving metrics untouched", file=sys.stderr)
        return None

    when = datetime.date.today().strftime("%B %Y")
    return (
        f"{M_BEGIN}\n"
        f'      <span id="metrics">{cites} citations &middot; h-index {h} &middot; '
        f"i10-index {i10} &nbsp;&mdash;&nbsp; "
        f'<a href="https://openalex.org/{author_id}" target="_blank" rel="noopener">'
        f"as indexed by OpenAlex</a>, {when}. "
        f"Google Scholar counts more sources and reports higher.</span>\n"
        f"      {M_END}"
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--orcid", default="0000-0002-9892-8282")
    ap.add_argument("--author", default=OPENALEX_AUTHOR,
                    help="OpenAlex author ID used for the citation metrics")
    ap.add_argument("--max", type=int, default=6)
    ap.add_argument("--file", default="index.html")
    args = ap.parse_args()

    path = pathlib.Path(args.file)
    src = path.read_text(encoding="utf-8")
    updated = src
    notes = []

    # --- news, from ORCID ------------------------------------------------
    items = []
    try:
        items = works(fetch(args.orcid))
    except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as e:
        # A transient ORCID outage must not fail the scheduled job or, worse,
        # blank the news list. Leave that block exactly as it is.
        print(f"ORCID unreachable ({e}); leaving news untouched", file=sys.stderr)

    if items:
        block = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
        if not block.search(updated):
            print("news markers not found in index.html", file=sys.stderr)
            return 1
        before, updated = updated, block.sub(
            lambda _m: render(items[: args.max]), updated, count=1)
        if updated != before:
            notes.append(f"{len(items[:args.max])} news entries, "
                         f"newest {items[0]['date']}")
    else:
        print("no usable ORCID works; leaving news untouched", file=sys.stderr)

    # --- metrics, from OpenAlex ------------------------------------------
    mblock = metrics_block(args.author)
    if mblock:
        pat = re.compile(re.escape(M_BEGIN) + r".*?" + re.escape(M_END), re.S)
        if not pat.search(updated):
            print("metrics markers not found in index.html", file=sys.stderr)
            return 1
        before, updated = updated, pat.sub(lambda _m: mblock, updated, count=1)
        if updated != before:
            notes.append("metrics")

    if updated == src:
        print("no change")
        return 0

    path.write_text(updated, encoding="utf-8")
    print("CHANGED — " + "; ".join(notes))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
